### ISSUE TITLE
how to set dataset for LR

### ISSUE THREAD

**Issue by hzjry123** [neal668/LightGBM-GBDT-LR#1]
hi，I want to know how to get dataset for LR from the decision tree~ Some papers says getting the features from tree nodes，but I don‘t know how~

**Comment by neal668** [comment]
Hi,

sorry to reply you so late.

the main idea of GBDT+LR is put forwarded by Facebook in the year 2014, you
may search "Facebook" + "GBDT+LR" to find the paper then have better
understanding.

simply speaking, the GBDT made an unlinear transform for input data. the
leaf node in GBDT where the test data fallen in will be treated as 1 while
others as 0, thus the input data will be transformed into a binary data
(0,0,0...1,0,0..0) then this data will be used for LR learning.

hope this answer can help you.

best,
Neal Tian

Quoting hzjry123 <notifications@github.com>:

> hi，I want to know how to get dataset for LR from the decision tree~
Some
> papers says getting the features from tree nodes，but I don‘t know
how~
>
>   —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
thread[2].
>       



Links:
------
[1]  
https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_neal668_LightGBM-2DGBDT-2DLR_issues_1&d=BQMFaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=4qVxDU18bcovGDm3aZUwgw&m=FKuMo0FQTjCHPFxrMklf8AL_XAvKnyIHt8QZjPtdH7M&s=Ikzbw_OculfKFkyPJlav4AcrozIePAcnW4gO8EmCvE0&e=
[2]  
https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AO8EYgkPYpLSiVuOeyb6fiBi9XfcBDwbks5r7IbsgaJpZM4NflxF&d=BQMFaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=4qVxDU18bcovGDm3aZUwgw&m=FKuMo0FQTjCHPFxrMklf8AL_XAvKnyIHt8QZjPtdH7M&s=ElpUv9TdGIOHgYG2ajE2io8cdmJNrxdOebnTqilI4Ys&e=
